# Goreleaser configuration for Wails v2 Pub/Sub GUI application
version: 2
project_name: pubsub-gui

# Build hooks - ensure dependencies are tidy before Go compilation
# Note: Frontend is built in GitHub Actions workflow before GoReleaser runs
before:
  hooks:
    - go mod tidy

# Build configuration
# Note: Frontend must be built before running Goreleaser (see GitHub Actions workflow)
builds:
  - id: pubsub-gui
    env:
      - CGO_ENABLED=1
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    goarm:
      - "7" # for ARMv7
    # Skip unsupported combinations
    ignore:
      - goos: windows
        goarch: arm64 # Windows ARM64 not commonly supported
      - goos: linux
        goarch: arm64 # Linux ARM64 cross-compilation requires CGO toolchain (Wails needs CGO)
    dir: .
    main: .
    binary: pubsub-gui
    flags:
      - -trimpath
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}

# Archive configuration
archives:
  - id: default
    format_overrides:
      - goos: windows
        formats:
          - zip
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}_{{ .Version }}"
    files:
      - README.md
      - LICENSE
      - "*.md"

# Checksums
checksum:
  name_template: "{{ .ProjectName }}_{{ .Version }}_checksums.txt"
  algorithm: sha256

# Snapshots (for development builds)
# Empty snapshot config uses defaults
snapshot: {}

# Changelog
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"

# GitHub release
release:
  github:
    owner: "{{ .Env.GITHUB_OWNER }}" # Set in GitHub Actions
    name: "{{ .Env.GITHUB_REPO_NAME }}" # Set in GitHub Actions
  mode: replace
  header: |
    ## Release {{ .Tag }}

    Published on {{ .Date }}
  footer: |
    ## Installation

    Download the appropriate binary for your platform:
    - **macOS**: `pubsub-gui_darwin_amd64_{{ .Version }}.tar.gz` or `pubsub-gui_darwin_arm64_{{ .Version }}.tar.gz`
    - **Windows**: `pubsub-gui_windows_amd64_{{ .Version }}.zip`
    - **Linux**: `pubsub-gui_linux_amd64_{{ .Version }}.tar.gz`

    Note: Linux ARM64 builds are not available due to CGO cross-compilation requirements. Use the amd64 build or build from source.

    Extract the archive and run the `pubsub-gui` binary.

    For installers (DMG, NSIS, AppImage), see the release notes for platform-specific instructions.

# Homebrew tap (optional - for macOS users)
# Uncomment and configure if you want to publish to Homebrew
# brews:
#   - name: pubsub-gui
#     homepage: "https://github.com/yourusername/pubsub-gui"
#     description: "GUI for Google Cloud Pub/Sub management"
#     license: "MIT"
#     test: |
#       system "#{bin}/pubsub-gui --version"
#     install: |
#       bin.install "pubsub-gui"

# Scoop manifest (optional - for Windows users)
# Uncomment and configure if you want to publish to Scoop
# scoops:
#   - name: pubsub-gui
#     homepage: "https://github.com/yourusername/pubsub-gui"
#     description: "GUI for Google Cloud Pub/Sub management"
#     license: "MIT"
#     architecture:
#       amd64:
#         url: "https://github.com/yourusername/pubsub-gui/releases/download/{{ .Tag }}/pubsub-gui_windows_amd64.zip"
#         sha256: "{{ .WindowsAmd64.Sha256 }}"
#         bin: "pubsub-gui.exe"

# Docker (optional - if you want to containerize)
# dockers:
#   - goos: linux
#     goarch: amd64
#     image_templates:
#       - "yourusername/pubsub-gui:{{ .Tag }}"
#       - "yourusername/pubsub-gui:latest"
#     dockerfile: Dockerfile

# macOS Universal Binary (Intel + Apple Silicon)
# Note: DMG creation requires additional tools (create-dmg, hdiutil)
# See: https://github.com/create-dmg/create-dmg
# For code signing, you'll need Developer ID certificates
universal_binaries:
  - id: default
    replace: true

# Windows NSIS installer
# Note: NSIS installer creation requires:
# 1. NSIS installed on Windows build machine
# 2. Custom script or post-build hook to create installer
# 3. Code signing certificates for Windows (optional but recommended)
# See: https://nsis.sourceforge.io/

# Linux AppImage
# Note: AppImage creation requires:
# 1. appimagetool (https://github.com/AppImage/AppImageKit)
# 2. Custom script or post-build hook
# 3. Desktop integration files (.desktop, icon)
# See: https://appimage.org/

# Installer creation can be added as post-build hooks or separate GitHub Actions steps
# Example post-build hook:
# post_hooks:
#   - cmd: scripts/create-dmg.sh
#     dir: dist
#   - cmd: scripts/create-nsis.sh
#     dir: dist
#   - cmd: scripts/create-appimage.sh
#     dir: dist

# NFPM (for .deb and .rpm packages - optional)
nfpms:
  - id: default
    package_name: pubsub-gui
    file_name_template: "{{ .ConventionalFileName }}"
    maintainer: "Bernat <b.barroso8@gmail.com>"
    vendor: "Bernat"
    description: "GUI for Google Cloud Pub/Sub management"
    license: "MIT"
    formats:
      - deb
      - rpm
    bindir: /usr/bin
    contents:
      - src: "{{ .ArtifactPath }}"
        dst: /usr/bin/pubsub-gui
        file_info:
          mode: 0755
