# Goreleaser configuration for Wails v2 Pub/Sub GUI application
project_name: pubsub-gui

# Build configuration
# Note: Frontend must be built before running Goreleaser (see GitHub Actions workflow)
builds:
  - id: pubsub-gui
    env:
      - CGO_ENABLED=1
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    goarm:
      - "7" # for ARMv7
    # Skip unsupported combinations
    ignore:
      - goos: windows
        goarch: arm64 # Windows ARM64 not commonly supported
    dir: .
    main: .
    binary: pubsub-gui

# Archive configuration
archives:
  - id: default
    builds:
      - pubsub-gui
    format_overrides:
      - goos: windows
        format: zip
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}_{{ .Version }}"
    files:
      - README.md
      - LICENSE
      - "*.md"

# Checksums
checksum:
  name_template: "{{ .ProjectName }}_{{ .Version }}_checksums.txt"
  algorithm: sha256

# Snapshots (for development builds)
snapshot:
  name_template: "{{ .Tag }}-next"

# Changelog
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"

# GitHub release
release:
  github:
    owner: "{{ .Env.GITHUB_OWNER }}" # Set in GitHub Actions
    name: "{{ .Env.GITHUB_REPOSITORY }}" # Set in GitHub Actions
  mode: replace
  header: |
    ## Release {{ .Tag }}

    Published on {{ .Date }}
  footer: |
    ## Installation

    Download the appropriate binary for your platform:
    - **macOS**: `pubsub-gui_darwin_amd64.tar.gz` or `pubsub-gui_darwin_arm64.tar.gz`
    - **Windows**: `pubsub-gui_windows_amd64.zip`
    - **Linux**: `pubsub-gui_linux_amd64.tar.gz` or `pubsub-gui_linux_arm64.tar.gz`

    Extract the archive and run the `pubsub-gui` binary.

# Homebrew tap (optional - for macOS users)
# Uncomment and configure if you want to publish to Homebrew
# brews:
#   - name: pubsub-gui
#     homepage: "https://github.com/yourusername/pubsub-gui"
#     description: "GUI for Google Cloud Pub/Sub management"
#     license: "MIT"
#     test: |
#       system "#{bin}/pubsub-gui --version"
#     install: |
#       bin.install "pubsub-gui"

# Scoop manifest (optional - for Windows users)
# Uncomment and configure if you want to publish to Scoop
# scoops:
#   - name: pubsub-gui
#     homepage: "https://github.com/yourusername/pubsub-gui"
#     description: "GUI for Google Cloud Pub/Sub management"
#     license: "MIT"
#     architecture:
#       amd64:
#         url: "https://github.com/yourusername/pubsub-gui/releases/download/{{ .Tag }}/pubsub-gui_windows_amd64.zip"
#         sha256: "{{ .WindowsAmd64.Sha256 }}"
#         bin: "pubsub-gui.exe"

# Docker (optional - if you want to containerize)
# dockers:
#   - goos: linux
#     goarch: amd64
#     image_templates:
#       - "yourusername/pubsub-gui:{{ .Tag }}"
#       - "yourusername/pubsub-gui:latest"
#     dockerfile: Dockerfile

# NFPM (for .deb and .rpm packages - optional)
# nfpms:
#   - id: default
#     builds:
#       - pubsub-gui
#     package_name: pubsub-gui
#     file_name_template: "{{ .ConventionalFileName }}"
#     maintainer: "Bernat <b.barroso8@gmail.com>"
#     description: "GUI for Google Cloud Pub/Sub management"
#     license: "MIT"
#     formats:
#       - deb
#       - rpm
#     bindir: /usr/bin
#     contents:
#       - src: "{{ .ArtifactPath }}"
#         dst: /usr/bin/pubsub-gui
#         file_info:
#           mode: 0755
