// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {models} from '../models';
import {admin} from '../models';

export function ConnectWithADC(arg1:string):Promise<void>;

export function ConnectWithServiceAccount(arg1:string,arg2:string):Promise<void>;

export function DeleteProfile(arg1:string):Promise<void>;

export function Disconnect():Promise<void>;

export function GetConnectionStatus():Promise<main.ConnectionStatus>;

export function GetProfiles():Promise<Array<models.ConnectionProfile>>;

export function GetSubscriptionMetadata(arg1:string):Promise<admin.SubscriptionInfo>;

export function GetTopicMetadata(arg1:string):Promise<admin.TopicInfo>;

export function ListSubscriptions():Promise<Array<admin.SubscriptionInfo>>;

export function ListTopics():Promise<Array<admin.TopicInfo>>;

export function SaveProfile(arg1:models.ConnectionProfile):Promise<void>;

export function SwitchProfile(arg1:string):Promise<void>;
