// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ConnectWithADC(arg1) {
  return window['go']['main']['App']['ConnectWithADC'](arg1);
}

export function ConnectWithServiceAccount(arg1, arg2) {
  return window['go']['main']['App']['ConnectWithServiceAccount'](arg1, arg2);
}

export function DeleteProfile(arg1) {
  return window['go']['main']['App']['DeleteProfile'](arg1);
}

export function Disconnect() {
  return window['go']['main']['App']['Disconnect']();
}

export function GetConnectionStatus() {
  return window['go']['main']['App']['GetConnectionStatus']();
}

export function GetProfiles() {
  return window['go']['main']['App']['GetProfiles']();
}

export function GetSubscriptionMetadata(arg1) {
  return window['go']['main']['App']['GetSubscriptionMetadata'](arg1);
}

export function GetTopicMetadata(arg1) {
  return window['go']['main']['App']['GetTopicMetadata'](arg1);
}

export function ListSubscriptions() {
  return window['go']['main']['App']['ListSubscriptions']();
}

export function ListTopics() {
  return window['go']['main']['App']['ListTopics']();
}

export function SaveProfile(arg1) {
  return window['go']['main']['App']['SaveProfile'](arg1);
}

export function SwitchProfile(arg1) {
  return window['go']['main']['App']['SwitchProfile'](arg1);
}
