// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckEmulatorStatus(arg1) {
  return window['go']['main']['App']['CheckEmulatorStatus'](arg1);
}

export function CheckForUpdates() {
  return window['go']['main']['App']['CheckForUpdates']();
}

export function ClearMessageBuffer(arg1) {
  return window['go']['main']['App']['ClearMessageBuffer'](arg1);
}

export function ConnectWithADC(arg1, arg2) {
  return window['go']['main']['App']['ConnectWithADC'](arg1, arg2);
}

export function ConnectWithOAuth(arg1, arg2, arg3) {
  return window['go']['main']['App']['ConnectWithOAuth'](arg1, arg2, arg3);
}

export function ConnectWithServiceAccount(arg1, arg2, arg3) {
  return window['go']['main']['App']['ConnectWithServiceAccount'](arg1, arg2, arg3);
}

export function CreateFromTemplate(arg1) {
  return window['go']['main']['App']['CreateFromTemplate'](arg1);
}

export function CreateSnapshot(arg1, arg2) {
  return window['go']['main']['App']['CreateSnapshot'](arg1, arg2);
}

export function CreateSubscription(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreateSubscription'](arg1, arg2, arg3);
}

export function CreateTopic(arg1, arg2) {
  return window['go']['main']['App']['CreateTopic'](arg1, arg2);
}

export function DeleteCustomTopicSubscriptionTemplate(arg1) {
  return window['go']['main']['App']['DeleteCustomTopicSubscriptionTemplate'](arg1);
}

export function DeleteProfile(arg1) {
  return window['go']['main']['App']['DeleteProfile'](arg1);
}

export function DeleteSnapshot(arg1) {
  return window['go']['main']['App']['DeleteSnapshot'](arg1);
}

export function DeleteSubscription(arg1) {
  return window['go']['main']['App']['DeleteSubscription'](arg1);
}

export function DeleteTemplate(arg1) {
  return window['go']['main']['App']['DeleteTemplate'](arg1);
}

export function DeleteTopic(arg1) {
  return window['go']['main']['App']['DeleteTopic'](arg1);
}

export function Disconnect() {
  return window['go']['main']['App']['Disconnect']();
}

export function DismissUpgradeNotification(arg1) {
  return window['go']['main']['App']['DismissUpgradeNotification'](arg1);
}

export function GetAutoAck() {
  return window['go']['main']['App']['GetAutoAck']();
}

export function GetBufferedMessages(arg1) {
  return window['go']['main']['App']['GetBufferedMessages'](arg1);
}

export function GetConfigFileContent() {
  return window['go']['main']['App']['GetConfigFileContent']();
}

export function GetConnectionStatus() {
  return window['go']['main']['App']['GetConnectionStatus']();
}

export function GetCurrentVersion() {
  return window['go']['main']['App']['GetCurrentVersion']();
}

export function GetLogs(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetLogs'](arg1, arg2, arg3);
}

export function GetLogsFiltered(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['GetLogsFiltered'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function GetProfiles() {
  return window['go']['main']['App']['GetProfiles']();
}

export function GetSnapshot(arg1) {
  return window['go']['main']['App']['GetSnapshot'](arg1);
}

export function GetSubscriptionMetadata(arg1) {
  return window['go']['main']['App']['GetSubscriptionMetadata'](arg1);
}

export function GetTemplates(arg1) {
  return window['go']['main']['App']['GetTemplates'](arg1);
}

export function GetTopicMetadata(arg1) {
  return window['go']['main']['App']['GetTopicMetadata'](arg1);
}

export function GetTopicSubscriptionTemplates() {
  return window['go']['main']['App']['GetTopicSubscriptionTemplates']();
}

export function GetTopicSubscriptionTemplatesByCategory(arg1) {
  return window['go']['main']['App']['GetTopicSubscriptionTemplatesByCategory'](arg1);
}

export function GetVersion() {
  return window['go']['main']['App']['GetVersion']();
}

export function ListSnapshots() {
  return window['go']['main']['App']['ListSnapshots']();
}

export function ListSnapshotsForSubscription(arg1) {
  return window['go']['main']['App']['ListSnapshotsForSubscription'](arg1);
}

export function ListSubscriptions() {
  return window['go']['main']['App']['ListSubscriptions']();
}

export function ListTopics() {
  return window['go']['main']['App']['ListTopics']();
}

export function OpenReleasesPage(arg1) {
  return window['go']['main']['App']['OpenReleasesPage'](arg1);
}

export function PublishMessage(arg1, arg2, arg3) {
  return window['go']['main']['App']['PublishMessage'](arg1, arg2, arg3);
}

export function SaveConfigFileContent(arg1) {
  return window['go']['main']['App']['SaveConfigFileContent'](arg1);
}

export function SaveCustomTopicSubscriptionTemplate(arg1) {
  return window['go']['main']['App']['SaveCustomTopicSubscriptionTemplate'](arg1);
}

export function SaveProfile(arg1) {
  return window['go']['main']['App']['SaveProfile'](arg1);
}

export function SaveTemplate(arg1) {
  return window['go']['main']['App']['SaveTemplate'](arg1);
}

export function SeekToSnapshot(arg1, arg2) {
  return window['go']['main']['App']['SeekToSnapshot'](arg1, arg2);
}

export function SeekToTimestamp(arg1, arg2) {
  return window['go']['main']['App']['SeekToTimestamp'](arg1, arg2);
}

export function SetAutoAck(arg1) {
  return window['go']['main']['App']['SetAutoAck'](arg1);
}

export function SetVersion(arg1) {
  return window['go']['main']['App']['SetVersion'](arg1);
}

export function StartMonitor(arg1) {
  return window['go']['main']['App']['StartMonitor'](arg1);
}

export function StartPeriodicUpgradeCheck() {
  return window['go']['main']['App']['StartPeriodicUpgradeCheck']();
}

export function StartTopicMonitor(arg1, arg2) {
  return window['go']['main']['App']['StartTopicMonitor'](arg1, arg2);
}

export function StopMonitor(arg1) {
  return window['go']['main']['App']['StopMonitor'](arg1);
}

export function StopTopicMonitor(arg1) {
  return window['go']['main']['App']['StopTopicMonitor'](arg1);
}

export function SwitchProfile(arg1) {
  return window['go']['main']['App']['SwitchProfile'](arg1);
}

export function SyncResources() {
  return window['go']['main']['App']['SyncResources']();
}

export function UpdateFontSize(arg1) {
  return window['go']['main']['App']['UpdateFontSize'](arg1);
}

export function UpdateSubscription(arg1, arg2) {
  return window['go']['main']['App']['UpdateSubscription'](arg1, arg2);
}

export function UpdateTemplate(arg1, arg2) {
  return window['go']['main']['App']['UpdateTemplate'](arg1, arg2);
}

export function UpdateTheme(arg1) {
  return window['go']['main']['App']['UpdateTheme'](arg1);
}
