// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {version} from '../models';
import {models} from '../models';
import {subscriber} from '../models';
import {app} from '../models';
import {main} from '../models';
import {admin} from '../models';

export function CheckDockerAvailable():Promise<void>;

export function CheckEmulatorStatus(arg1:string):Promise<Record<string, any>>;

export function CheckForUpdates():Promise<version.UpdateInfo>;

export function ClearMessageBuffer(arg1:string):Promise<void>;

export function ConnectWithADC(arg1:string,arg2:string):Promise<void>;

export function ConnectWithOAuth(arg1:string,arg2:string,arg3:string):Promise<void>;

export function ConnectWithServiceAccount(arg1:string,arg2:string,arg3:string):Promise<void>;

export function CreateFromTemplate(arg1:models.TemplateCreateRequest):Promise<models.TemplateCreateResult>;

export function CreateSnapshot(arg1:string,arg2:string):Promise<void>;

export function CreateSubscription(arg1:string,arg2:string,arg3:number):Promise<void>;

export function CreateTopic(arg1:string,arg2:string):Promise<void>;

export function DeleteCustomTopicSubscriptionTemplate(arg1:string):Promise<void>;

export function DeleteProfile(arg1:string):Promise<void>;

export function DeleteSnapshot(arg1:string):Promise<void>;

export function DeleteSubscription(arg1:string):Promise<void>;

export function DeleteTemplate(arg1:string):Promise<void>;

export function DeleteTopic(arg1:string):Promise<void>;

export function Disconnect():Promise<void>;

export function DismissUpgradeNotification(arg1:string):Promise<void>;

export function GetAutoAck():Promise<boolean>;

export function GetBufferedMessages(arg1:string):Promise<Array<subscriber.PubSubMessage>>;

export function GetConfigFileContent():Promise<string>;

export function GetConnectionStatus():Promise<app.ConnectionStatus>;

export function GetCurrentVersion():Promise<string>;

export function GetEmulatorStatus(arg1:string):Promise<main.EmulatorStatus>;

export function GetLogs(arg1:string,arg2:number,arg3:number):Promise<Array<app.LogEntry>>;

export function GetLogsFiltered(arg1:string,arg2:string,arg3:string,arg4:string,arg5:number,arg6:number):Promise<app.FilteredLogsResult>;

export function GetProfiles():Promise<Array<models.ConnectionProfile>>;

export function GetSnapshot(arg1:string):Promise<admin.SnapshotInfo>;

export function GetSubscriptionMetadata(arg1:string):Promise<admin.SubscriptionInfo>;

export function GetTemplates(arg1:string):Promise<Array<models.MessageTemplate>>;

export function GetTopicMetadata(arg1:string):Promise<admin.TopicInfo>;

export function GetTopicSubscriptionTemplates():Promise<Array<models.TopicSubscriptionTemplate>>;

export function GetTopicSubscriptionTemplatesByCategory(arg1:string):Promise<Array<models.TopicSubscriptionTemplate>>;

export function GetVersion():Promise<string>;

export function ListSnapshots():Promise<Array<admin.SnapshotInfo>>;

export function ListSnapshotsForSubscription(arg1:string):Promise<Array<admin.SnapshotInfo>>;

export function ListSubscriptions():Promise<Array<admin.SubscriptionInfo>>;

export function ListTopics():Promise<Array<admin.TopicInfo>>;

export function OpenReleasesPage(arg1:string):Promise<void>;

export function PublishMessage(arg1:string,arg2:string,arg3:Record<string, string>):Promise<main.PublishResult>;

export function SaveConfigFileContent(arg1:string):Promise<void>;

export function SaveCustomTopicSubscriptionTemplate(arg1:models.TopicSubscriptionTemplate):Promise<void>;

export function SaveProfile(arg1:models.ConnectionProfile):Promise<void>;

export function SaveTemplate(arg1:models.MessageTemplate):Promise<void>;

export function SeekToSnapshot(arg1:string,arg2:string):Promise<void>;

export function SeekToTimestamp(arg1:string,arg2:string):Promise<void>;

export function SetAutoAck(arg1:boolean):Promise<void>;

export function SetVersion(arg1:string):Promise<void>;

export function StartManagedEmulator(arg1:string):Promise<void>;

export function StartMonitor(arg1:string):Promise<void>;

export function StartPeriodicUpgradeCheck():Promise<void>;

export function StartTopicMonitor(arg1:string,arg2:string):Promise<void>;

export function StopManagedEmulator(arg1:string):Promise<void>;

export function StopMonitor(arg1:string):Promise<void>;

export function StopTopicMonitor(arg1:string):Promise<void>;

export function SwitchProfile(arg1:string):Promise<void>;

export function SyncResources():Promise<void>;

export function UpdateFontSize(arg1:string):Promise<void>;

export function UpdateSubscription(arg1:string,arg2:app.SubscriptionUpdateParams):Promise<void>;

export function UpdateTemplate(arg1:string,arg2:models.MessageTemplate):Promise<void>;

export function UpdateTheme(arg1:string):Promise<void>;
