// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {subscriber} from '../models';
import {main} from '../models';
import {models} from '../models';
import {admin} from '../models';

export function ClearMessageBuffer(arg1:string):Promise<void>;

export function ConnectWithADC(arg1:string):Promise<void>;

export function ConnectWithServiceAccount(arg1:string,arg2:string):Promise<void>;

export function CreateSubscription(arg1:string,arg2:string,arg3:number):Promise<void>;

export function CreateTopic(arg1:string,arg2:string):Promise<void>;

export function DeleteProfile(arg1:string):Promise<void>;

export function DeleteSubscription(arg1:string):Promise<void>;

export function DeleteTemplate(arg1:string):Promise<void>;

export function DeleteTopic(arg1:string):Promise<void>;

export function Disconnect():Promise<void>;

export function GetAutoAck():Promise<boolean>;

export function GetBufferedMessages(arg1:string):Promise<Array<subscriber.PubSubMessage>>;

export function GetConnectionStatus():Promise<main.ConnectionStatus>;

export function GetProfiles():Promise<Array<models.ConnectionProfile>>;

export function GetSubscriptionMetadata(arg1:string):Promise<admin.SubscriptionInfo>;

export function GetTemplates(arg1:string):Promise<Array<models.MessageTemplate>>;

export function GetTopicMetadata(arg1:string):Promise<admin.TopicInfo>;

export function ListSubscriptions():Promise<Array<admin.SubscriptionInfo>>;

export function ListTopics():Promise<Array<admin.TopicInfo>>;

export function PublishMessage(arg1:string,arg2:string,arg3:Record<string, string>):Promise<main.PublishResult>;

export function SaveProfile(arg1:models.ConnectionProfile):Promise<void>;

export function SaveTemplate(arg1:models.MessageTemplate):Promise<void>;

export function SetAutoAck(arg1:boolean):Promise<void>;

export function StartMonitor(arg1:string):Promise<void>;

export function StartTopicMonitor(arg1:string):Promise<void>;

export function StopMonitor(arg1:string):Promise<void>;

export function StopTopicMonitor(arg1:string):Promise<void>;

export function SwitchProfile(arg1:string):Promise<void>;

export function UpdateSubscription(arg1:string,arg2:main.SubscriptionUpdateParams):Promise<void>;

export function UpdateTemplate(arg1:string,arg2:models.MessageTemplate):Promise<void>;
